name: Read file
author: nikesh6920
description: 'Read file contents'
inputs:
  path:
    description: 'File path'
    required: true
  trim:
    description: 'Trims output'
    required: false
    default: false
outputs:
  content:
    description: 'File content'
runs:
  using: 'node16'
  main: 'dist/index.js'
