name: Simple Test Workflow
on: workflow_dispatch
#  push:
#  pull_request:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
#     - uses: ./.github/actions/checkout-action

    - name: Set up JDK 11
#      uses: ./.github/actions/java-setup
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      run: |
          mvn -B package --file pom.xml
          cd target && ls
          cd .. && ls -a
          cd .github/workflows && ls -a

    - name: Reading the spec file
      uses: demorepo/.github/workflows/readFile.yml@master
      with:
        gitRepo: ${{ github.repository }}
        gitBranch: ${{ github.ref }}
 
           
#    - name: Veracode Upload And Scan
#      uses: veracode/veracode-uploadandscan-action@0.2.1
#      with:
#        appname: 'VeraDemo'
#        createprofile: true
#        filepath: 'target/*.war'
#        vid: '${{ secrets.API_ID }}'
#        vkey: '${{ secrets.API_KEY }}'
#        createsandbox: 'true'
#        sandboxname: 'SANDBOXNAME'
#        scantimeout: 0
#        exclude: '*.js'
#        include: '*.war'
#        criticality: 'VeryHigh'
